#!/bin/bash

raml="$(grep 'RAM instance.*bootraml' exemplar.log | tail -1 | cut -f2 -d "'")_ix38"
ramh="$(grep 'RAM instance.*bootramh' exemplar.log | tail -1 | cut -f2 -d "'")_ix38"
awk "/\(instance $ramh/"' { print; print "      (property LPM_FILE (string \"bootramh.mif\"))" }
'"/\(instance $raml/"' { print; print "      (property LPM_FILE (string \"bootraml.mif\"))" }
!/\(instance ('"$ramh|$raml"')/ { print }' <b16_eval.edf >b16.edf
